### ISSUE TITLE
Pamac-pacaur

### ISSUE THREAD

**Issue by phenri** [SwagArch/swagarch-packages#1]
pamac-aur instead of pamac-pacaur? actually aur are not supported with the current installed pamac-pacaur. The pacaur dependency are not installable. Personally I uninstalled pamac-pacaur for pamac-aur.

**Comment by memoryleakx** [comment]
ok, in the next release I will switch back to **pamac-aur** 
I had decided to "pamac-pacaur" because "pamac-aur" was outdated at this time.

**Comment by memoryleakx** [comment]
remove pamac-pacaur and add pamac-aur package 
[https://github.com/SwagArch/swagarch-packages/commit/29cf7fd54a46df2d1b68529f6c8ac61529fef325](url)
